---
title: "GY460_Spatial_Accomodation Data"
author: "Allegra Saggese"
date: "4/14/2019"
output: html_document
---

```{r setup, include=FALSE}

library(rvest)
library(tidyr)
library(stringr) 
library(XML)
library(httr)

```

```{r, include=TRUE}

##use this to get the spatial data points of tourist locations
file <- xmlParse("http://servisi.azo.hr/priroda/wms?request=GetCapabilities")
class(file)
roots <- xmlRoot(file)

geog_node <- xmlChildren(file, search =Service)
set <- getNodeSet(file, "//EX_GeographicBoundingBox")
xmlSApply(set, xmlValue) 

# Trying using xml_find_all here instead
file = read_xml('http://servisi.azo.hr/priroda/wms?request=GetCapabilities')
test = xml_find_all(file, '//Layer')
test = xml_find_all(file, '//EX_GeographicBoundingBox')
```

```{r}
rooty = xml_root(file)
child1 = xml_child(rooty, search = 2)
child2 = xml_child(child1, search = 4)
listForm = as_list(child2)
isLayer = names(listForm) == 'Layer'
listForm = listForm[isLayer]
finalDf = matrix(nrow = 1, ncol = 5) %>%
  data.frame()
carDirecs = c("westBoundLongitude",
                        "eastBoundLongitude",
                        "southBoundLatitude",
                        "northBoundLatitude")
names(finalDf) = c('Title', carDirecs)
for(i in 1:length(listForm)){
  curLayer = listForm[i]
  finalDf[i,1] = curLayer$Layer$Title
  curBndBox = curLayer$Layer$EX_GeographicBoundingBox
  for(j in carDirecs){
    finalDf[i,j] = curBndBox[[j]]
  }
}
```


```{r, include=TRUE}
c=1:66
d=15
e=c*d

site_loop <- paste('https://www.booking.com/searchresults.en-us.html?label=gen173nr-1FCAEoggI46AdIM1gEaFCIAQGYATG4AQfIAQzYAQHoAQH4AQKIAgGoAgO4ApWbzuUFwAIB&sid=fec4720dd530160d33c2fe8791573d39&tmpl=searchresults&ac_click_type=b&ac_position=0&checkin_month=6&checkin_monthday=1&checkin_year=2019&checkout_month=6&checkout_monthday=2&checkout_year=2019&class_interval=1&dest_id=54&dest_type=country&dtdisc=0&from_sf=1&group_adults=2&group_children=0&inac=0&index_postcard=0&label_click=undef&no_rooms=1&postcard=0&raw_dest_type=country&room1=A%2CA&sb_price_type=total&search_selected=1&shw_aparth=1&slp_r_match=0&src=index&src_elem=sb&srpvid=fdcc8e4742ce00c6&ss=Croatia&ss_all=0&ss_raw=croatia&ssb=empty&sshis=0&rows=15&offset=', e, sep="")

dfList <- lapply(site_loop, function(i) {
    final_site <- read_html(i)
    draft_table <- htmlParse(final_site, 'span')
})

```

